name: CI Tests

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**.md'
      - '.gitignore'
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'

jobs:
  ci-tests:
    runs-on: ${{ matrix.os }}
    env:
      ci_tests: true
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        emacs_version:
          - 28.1
          - 28.2
          - 29.1
          - 29.2
          - 29.3
          - 29.4
          - snapshot
    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - uses: actions/checkout@v4
        with:
          path: '.emacs.d'

      - name: First start # So most modules are pulled in from melpa and gnu
        run: '.emacs.d/.ci/first-start.sh .emacs.d'

      # - name: Compilation # This pulls extra modules not enabled by default
      #   run: '.emacs.d/.ci/compilation.sh .emacs.d'

      - name: Unit tests
        run: '.emacs.d/.ci/unit-tests.sh .emacs.d'

      - name: Verify no obsolete cl- functions
        run: '.emacs.d/.ci/unit-test-cl.sh .emacs.d'

  pkryger-taps:
    runs-on: ${{ matrix.os }}
    env:
      ci_tests: true
    strategy:
      matrix:
        include:
          - os: macos-latest
            emacs_version: snapshot
    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - uses: actions/checkout@v4
        with:
          path: '.emacs.d'

      - uses: actions/checkout@v4
        with:
          repository: 'pkryger/exordium-commontap'
          path: '.emacs.d/taps/commontap'

      - name: First start # So most modules are pulled in from melpa and gnu
        run: '.emacs.d/.ci/first-start.sh .emacs.d'
